### ISSUE TITLE
Criar Banco de dados

### ISSUE THREAD

**Issue by GeisaNepomuceno** [GeisaNepomuceno/Cineclube#1]
# Critérios de aceite: 

- [ ] Estar pronto para integrar com o programa Java

## Tasks:
 
- [ ] Criar o banco de acordo com o MER apresentado para a professora
- [ ] Conseguir um host para o banco
