### ISSUE TITLE
Parte escrita do projeto

### ISSUE THREAD

**Issue by GeisaNepomuceno** [GeisaNepomuceno/Cineclube#11]
# Critérios de aceite: 

- [ ] Parte escrita do projeto estar pronto para ser entregue

## Tasks: 

- [ ] Introdução
- [ ] Papel das disciplinas
- [ ] Descrição do projeto prático
- [ ] Lições aprendidas e principais dificuldades
- [ ] Conclusões
- [ ] Ficha técnica que será apresentada a Fatec
