### ISSUE TITLE
Finalizar o programa Java

### ISSUE THREAD

**Issue by GeisaNepomuceno** [GeisaNepomuceno/Cineclube#2]
# Critérios de aceite: 

- [ ] Estar pronto para integrar com o banco de dados

## Tasks: 

- [ ] Fazer todas as telas que estarão disponíveis para o usuário 
- [ ] Fazer o CRUD dentro das telas 
- [ ] Verificar se o padrão MVC será feito
